import { useEffect, useRef, useState } from 'react'

const problems = [
  {
    num: '01',
    title: 'Insufficient AI oversight — their own words',
    quote: '"risks arising from insufficient human oversight of AI or a lack of controls and procedures monitoring the use of AI in day-to-day operations"',
    detail: "Medpace flagged this exact risk in their SEC annual report two years in a row. They're using AI for clinical trial endpoints but acknowledged they lack the oversight infrastructure to do it safely.",
    source: 'Medpace 10-K, Feb 2025',
    url: 'https://investor.medpace.com/static-files/cd41645f-da0e-40fb-9677-ba23376ffd6a',
    severity: 'critical',
    color: 'var(--red)',
    faint: 'var(--red-faint)',
  },
  {
    num: '02',
    title: '40% inter-reader variability without guardrails',
    quote: '"Without AI, sponsors see up to 40% variability on different radiologists\' readings of scans, as well as significant variability in the same radiologist\'s interpretation of the same scan on different occasions."',
    detail: "Medpace documented this in their own Medidata whitepaper. When AI does the measurements, that variability doesn't disappear — it shifts to AI confidence variance with no structured way to catch it.",
    source: 'Medpace + Medidata Whitepaper',
    url: 'https://www.medpace.com/blog/artificial-intelligence-can-boost-reliability-and-speed-of-medical-imaging-analysis-in-clinical-trials/',
    severity: 'high',
    color: 'var(--amber)',
    faint: 'var(--amber-faint)',
  },
  {
    num: '03',
    title: 'No QA layer between AI output and radiologist',
    quote: '"Results generated by AI imaging tools for clinical trial endpoints are reviewed and finally approved by appropriate medical experts."',
    detail: "Medpace Core Lab is already automating RECIST 1.1 preliminary measurements. But their own August 2025 whitepaper shows AI results go directly to radiologist review — no structured validation step in between.",
    source: 'Medpace AI Imaging Whitepaper, Aug 2025',
    url: 'https://www.medpace.com/wp-content/uploads/2025/08/Article-How-AI-and-ML-are-Transforming-the-Future-of-Medical-Imaging-in-Clinical-Trials.pdf',
    severity: 'high',
    color: 'var(--amber)',
    faint: 'var(--amber-faint)',
  },
  {
    num: '04',
    title: 'RECIST 1.1 errors have direct FDA consequences',
    quote: '"RECIST 1.1 response evaluation criteria for solid tumors is the only imaging endpoint that FDA officially accepts as a surrogate marker in oncology."',
    detail: "This isn't a quality-of-life issue. Errors in RECIST measurement directly affect regulatory decisions for the FDA's sole accepted surrogate marker in oncology trials.",
    source: 'Medpace Oncology Imaging',
    url: 'https://www.medpace.com/core-lab/imaging-core-lab/therapeutic-expertise/oncology-imaging/',
    severity: 'critical',
    color: 'var(--red)',
    faint: 'var(--red-faint)',
  },
]

function ProbCard({ p, index }) {
  const ref = useRef(null)
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setVisible(true) }, { threshold: 0.15 })
    if (ref.current) obs.observe(ref.current)
    return () => obs.disconnect()
  }, [])

  return (
    <div ref={ref} style={{
      background: 'var(--bg-1)',
      border: `1px solid var(--border)`,
      borderRadius: 'var(--radius-lg)',
      padding: '28px 30px',
      position: 'relative',
      overflow: 'hidden',
      opacity: visible ? 1 : 0,
      transform: visible ? 'translateY(0)' : 'translateY(30px)',
      transition: `all 0.65s cubic-bezier(0.16,1,0.3,1) ${index * 0.1}s`,
      cursor: 'default',
    }}
      onMouseEnter={e => {
        e.currentTarget.style.borderColor = p.color.replace('var(--', '').includes('red') ? 'rgba(255,71,87,0.3)' : 'rgba(255,165,2,0.3)'
        e.currentTarget.style.background = 'var(--bg-2)'
      }}
      onMouseLeave={e => {
        e.currentTarget.style.borderColor = 'var(--border)'
        e.currentTarget.style.background = 'var(--bg-1)'
      }}
    >
      <div style={{
        position: 'absolute', top: 0, left: 0, right: 0, height: 2,
        background: `linear-gradient(90deg, transparent, ${p.color}, transparent)`,
        opacity: 0.6,
      }} />

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
        <span style={{
          fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-tertiary)',
          letterSpacing: '0.1em',
        }}>PROBLEM {p.num}</span>
        <span style={{
          fontSize: 10, fontFamily: 'var(--font-mono)', letterSpacing: '0.08em',
          padding: '3px 9px', borderRadius: 4,
          background: p.faint, color: p.color,
          border: `1px solid ${p.color}`,
          opacity: 0.9,
        }}>{p.severity.toUpperCase()}</span>
      </div>

      <h3 style={{ fontSize: 17, fontWeight: 500, color: 'var(--text-primary)', marginBottom: 14, lineHeight: 1.35 }}>
        {p.title}
      </h3>

      <blockquote style={{
        borderLeft: `2px solid ${p.color}`,
        paddingLeft: 14,
        margin: '0 0 14px',
        fontSize: 13,
        color: 'var(--text-secondary)',
        lineHeight: 1.6,
        fontStyle: 'italic',
        opacity: 0.85,
      }}>
        {p.quote}
      </blockquote>

      <p style={{ fontSize: 13, color: 'var(--text-tertiary)', lineHeight: 1.6, marginBottom: 18 }}>
        {p.detail}
      </p>

      <a href={p.url} target="_blank" rel="noopener noreferrer" style={{
        display: 'inline-flex', alignItems: 'center', gap: 6,
        fontSize: 11, fontFamily: 'var(--font-mono)', letterSpacing: '0.06em',
        color: 'var(--text-tertiary)',
        background: 'var(--bg-3)',
        border: '1px solid var(--border)',
        borderRadius: 6, padding: '6px 12px',
        textDecoration: 'none',
        transition: 'all 0.2s',
      }}
        onMouseEnter={e => { e.currentTarget.style.color = 'var(--teal)'; e.currentTarget.style.borderColor = 'var(--border-accent)' }}
        onMouseLeave={e => { e.currentTarget.style.color = 'var(--text-tertiary)'; e.currentTarget.style.borderColor = 'var(--border)' }}
      >
        <span>↗</span> {p.source}
      </a>
    </div>
  )
}

export default function Problems() {
  const headRef = useRef(null)
  const [headVisible, setHeadVisible] = useState(false)

  useEffect(() => {
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setHeadVisible(true) }, { threshold: 0.3 })
    if (headRef.current) obs.observe(headRef.current)
    return () => obs.disconnect()
  }, [])

  return (
    <section style={{ padding: '100px 0', borderBottom: '1px solid var(--border)' }}>
      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 40px' }}>
        <div ref={headRef} style={{
          marginBottom: 56,
          opacity: headVisible ? 1 : 0,
          transform: headVisible ? 'translateY(0)' : 'translateY(20px)',
          transition: 'all 0.6s cubic-bezier(0.16,1,0.3,1)',
        }}>
          <div style={{
            fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--teal)',
            letterSpacing: '0.12em', marginBottom: 12,
          }}>THE PROBLEM</div>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 44px)', fontWeight: 300, letterSpacing: '-0.02em', lineHeight: 1.1 }}>
            Medpace documented these gaps
            <br />
            <span style={{ color: 'var(--text-tertiary)', fontWeight: 300 }}>in their own public filings</span>
          </h2>
        </div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(460px, 1fr))',
          gap: 16,
        }}>
          {problems.map((p, i) => <ProbCard key={p.num} p={p} index={i} />)}
        </div>
      </div>
    </section>
  )
}
